default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: SpendSmart_development

test:
  <<: *default
  database: SpendSmart_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

